apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-config
data:
  log4j2.xml: |
{{ .Files.Get "config/log4j2.xml" | indent 4 }}
  jmxExporter.config: |
{{ .Files.Get "config/jmx-exporter-config.yml" | indent 4 }}

